version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rbd_becom
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend-docker
    container_name: backend
    expose:
      - "8090"
    depends_on:
      - mysql
    restart: always   # ✅ 추가
    environment:
      SPRING_PROFILES_ACTIVE: docker # Spring docker Profile 사용
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rbd_becom?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build:
      context: ./frontend-docker
      dockerfile: Dockerfile
      args:
        - ENV=prod
    container_name: frontend
    ports:
      - "8080:80" # Host:8080, Container:80
    restart: always
    depends_on:
      - backend

volumes:
  mysql-data: